/*
 * SME South Africa — Mockup release status (the gate config).
 * Generated by control.html.
 * Allowed: "finalised" | "under-review" | "under-work" | "not-started"
 */
window.MOCKUP_STATUS = {
  "public-home.html": "under-work",
  "public-articles.html": "finalised",
  "public-article-categories.html": "finalised",
  "public-category.html": "finalised",
  "public-subcategory.html": "finalised",
  "public-author.html": "finalised",
  "public-article.html": "finalised",
  "public-resources.html": "under-review",
  "public-resource-category.html": "under-review",
  "public-resource.html": "under-review",
  "public-funding.html": "under-review",
  "public-funding-category.html": "under-review",
  "public-loan-option.html": "under-review",
  "public-solutions.html": "under-review",
  "public-solution-category.html": "under-review",
  "public-sustainability.html": "under-review",
  "public-pricing.html": "under-review",
  "public-brands.html": "under-review",
  "public-brand.html": "under-review",
  "public-deals.html": "under-review",
  "public-deal.html": "under-review",
  "public-guides.html": "under-review",
  "public-guide.html": "under-review",
  "public-founder-focus.html": "under-review",
  "public-shop.html": "under-review",
  "public-checkout.html": "under-review",
  "public-auth.html": "finalised",
  "public-about.html": "finalised",
  "public-contact.html": "finalised",
  "public-advertise.html": "finalised",
  "public-privacy.html": "finalised",
  "public-terms.html": "finalised",
  "public-refunds.html": "finalised",
  "public-popia.html": "finalised",
  "public-advertising-disclosure.html": "under-review",
  "member-hub.html": "under-review",
  "members.html": "under-review",
  "single-group.html": "under-review",
  "forums.html": "under-review",
  "member-account.html": "under-review",
  "events.html": "under-review",
  "newsletter.html": "under-review",
  "newsletter-issue.html": "under-review",
  "podcast.html": "under-work",
  "brand_ci.html": "finalised",
  "public-icons.html": "finalised",
  "handbook.html": "finalised",
  "public-help.html": "under-review",
  "public-help-article.html": "under-review",
  "public-search.html": "under-review",
  "public-404.html": "under-review"
};
window.MOCKUP_STATUS_PUBLISHED = "2026-06-23T13:25:52.117Z";
/* Developer builds (staging) — { mockup file: { url, status } }; status: "pending-review" | "reviewed" | "approved" */
window.MOCKUP_DEV = {
  "public-home.html": {"url":"https://smesastg.wpengine.com/","status":"pending-review"}
};
/* Group overrides — { mockup file: "Group name" }; overrides default NAV grouping in index.html */
window.MOCKUP_GROUPS = {};
