/*
 * SME South Africa — Mockup release status (the gate config).
 * Generated by control.html.
 * Allowed: "finalised" | "under-review" | "under-work" | "not-started"
 */
window.MOCKUP_STATUS = {
  "public-home.html": "finalised",
  "public-articles.html": "finalised",
  "public-article-categories.html": "finalised",
  "public-category.html": "under-review",
  "public-subcategory.html": "under-review",
  "public-author.html": "under-review",
  "public-article.html": "under-review",
  "public-resources.html": "under-review",
  "public-resource-category.html": "under-review",
  "public-resource.html": "under-review",
  "public-funding.html": "under-review",
  "public-funding-category.html": "under-review",
  "public-loan-option.html": "under-review",
  "public-solutions.html": "under-review",
  "public-solution-category.html": "under-review",
  "public-solution-review.html": "under-review",
  "public-shop.html": "under-review",
  "public-checkout.html": "under-review",
  "public-auth.html": "finalised",
  "public-about.html": "finalised",
  "public-contact.html": "finalised",
  "public-advertise.html": "finalised",
  "public-privacy.html": "finalised",
  "public-terms.html": "finalised",
  "public-refunds.html": "finalised",
  "public-popia.html": "finalised",
  "member-hub.html": "finalised",
  "members.html": "under-review",
  "single-group.html": "under-review",
  "forums.html": "under-review",
  "member-account.html": "under-review",
  "events.html": "finalised",
  "newsletter.html": "under-review",
  "newsletter-issue.html": "under-review",
  "podcast.html": "under-work",
  "brand_ci.html": "finalised",
  "public-icons.html": "finalised"
};
window.MOCKUP_STATUS_PUBLISHED = "2026-06-15T10:21:06.161Z";
